apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/load-balancer-type: Internal
  name: {{Servicename}}
spec:
  type: {{serviceType}}
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: {{name}}